# Generated by Django 3.1.3 on 2023-03-26 01:10

from django.db import migrations, models
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_auto_20230326_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', simplemde.fields.SimpleMDEField(verbose_name='mardown content')),
            ],
        ),
    ]
